### ISSUE TITLE
Advice Please

### ISSUE THREAD

**Issue by senseiweb** [pleerock/gulpclass#10]
Not sure how I am getting this wrong...followed the instructions however the tasks for the gulpfile are not being listed. I am using the standard gulpfile.ts used on this site and here is my gulpfile.js 

``` typescript
var tsOptions = {
    emitDecoratorMetadata: true,
    experimentalDecorators: true,
    noEmitOnError: false,
    module: "commonjs",
    target: "es5",
    outDir: "./tasks"
}
var files = [
    "/gulpfile.ts"
    ];
files.forEach(function(file) {
    var ts1 = require("typescript").transpile(require("fs").readFileSync(file).toString(), tsOptions);
    console.log(ts1);
    eval(require("typescript").transpile(require("fs").readFileSync(file).toString()), tsOptions);
    });
```

I am console log the output of the ts compilation  

``` javascript
"use strict";
var __decorate = (this && this.__decorate) || function (decorators, target, key, desc) {
    var c = arguments.length, r = c < 3 ? target : desc === null ? desc = Object.getOwnPropertyDescriptor(target, key) : desc, d;
    if (typeof Reflect === "object" && typeof Reflect.decorate === "function") r = Reflect.decorate(decorators, target, key, desc);
    else for (var i = decorators.length - 1; i >= 0; i--) if (d = decorators[i]) r = (c < 3 ? d(r) : c > 3 ? d(target, key, r) : d(target, key)) || r;
    return c > 3 && r && Object.defineProperty(target, key, r), r;
};
var Decorators_1 = require("gulpclass/Decorators");
var gulp = require("gulp");
var del = require("del");
var Gulpfile = (function () {
    function Gulpfile() {
    }
    Gulpfile.prototype.clean = function (cb) {
        return del(["./dist/**"], cb);
    };
    Gulpfile.prototype.sayHello = function () {
        return 'Hello, I am working';
    };
    Gulpfile.prototype.copySourceFiles = function () {
        return gulp.src(["./src/**.js"])
            .pipe(gulp.dest("./dist/src"));
    };
    Gulpfile.prototype.build = function () {
        return ["copyFiles", "copy-source-files"];
    };
    Gulpfile.prototype.default = function () {
        return ["build"];
    };
    __decorate([
        Decorators_1.Task()
    ], Gulpfile.prototype, "clean", null);
    __decorate([
        Decorators_1.Task()
    ], Gulpfile.prototype, "sayHello", null);
    __decorate([
        Decorators_1.Task("copy-source-files")
    ], Gulpfile.prototype, "copySourceFiles", null);
    __decorate([
        Decorators_1.SequenceTask()
    ], Gulpfile.prototype, "build", null);
    __decorate([
        Decorators_1.Task()
    ], Gulpfile.prototype, "default", null);
    Gulpfile = __decorate([
        Decorators_1.Gulpclass()
    ], Gulpfile);
    return Gulpfile;
}());
exports.Gulpfile = Gulpfile;
```

However we I run a task listing the only tasks that appear is "Gulpfile" and I am unable to run of any of the other task.  I am using VS 2015 with Gulp-cli 1.2.1 and 3.9.1 (downgraded from 4.0 alpha 2)...any idea what I am doing wrong?

**Comment by pleerock** [comment]
what is `a task listing`? For me it seems like some dropdown in the visual studio, that lists all tasks from the gulpfile. If so, then its most probably it will not work, since ms visual studio needs to add support of it. But it should work with a command line, did you try to run `gulp yourTask` from command line?

**Comment by senseiweb** [comment]
Thanks for the quick reply -- see my clarification below:

From a windows command line, here is what I am getting:

```
PS [0727]  FrontEnd /> gulp --tasks
[07:29:43] Tasks for ~\Documents\Visual Studio 2015\Projects\EpmeCourseAppTool\FrontEnd\gulpfile.js
[07:29:43] └── Gulpfile
PS [0729]  FrontEnd /> gulp clean
[07:29:50] Using gulpfile ~\Documents\Visual Studio 2015\Projects\EpmeCourseAppTool\FrontEnd\gulpfile.js
[07:29:50] Task 'clean' is not in your gulpfile
[07:29:50] Please check the documentation for proper gulpfile formatting
```

Also not sure it matters, but I am the above was ran with typescript 1.9 [nightly], but I did downgrade to 1.8 [latest stable] and condition still exists.

**Comment by senseiweb** [comment]
So it appears, having gulp 4 installed was the problem; however downgrading back to gulp 3.9.1 does NOT seem to correct the problems that gulp 4 introduced. Also tried clearing the npm cache after the uninstall without any success. Any suggestions?

Steps to repeat:
npm uninstall gulp
npm install "gulpjs/gulp#4.0" 
gulp --tasks (only tasks displayed is 'Gulpfile')
npm uninstall gulp 
npm install gulp
gulp --tasks (still broken)

**Comment by pleerock** [comment]
looks like tasks list wont work with dynamic gulpfile.js. I suggest you to try to install ts-node and use gulp class with it. This way gulp --tasks should work

**Comment by pleerock** [comment]
can this be closed?
