### ISSUE TITLE
let gulp = require("gulp"); let del = require("del") - require symbol not being found

### ISSUE THREAD

**Issue by st-clair-clarke** [pleerock/gulpclass#12]
Hi,
I am following your example. However, the statements

``` typescript
let gulp = require("gulp");
let del = require("del");
```

are not resolved in my gulpclass.ts

Where is this require method supposed to be? My stackoverflow investigation leads to more confusion.

Thanks

**Comment by pleerock** [comment]
what do you mean by **are not resolved in my gulpclass.ts** ? its just dependencies you should install and use

**Comment by st-clair-clarke** [comment]
I see require and requirejs at npm repo. Which one should I install?

**Comment by pleerock** [comment]
its not clear what problem you have. require is nodejs function, what are you trying to install? there is nothing else you should install with gulpclass. only gulpclass - everything else depends of your needs
