### ISSUE TITLE
@SequenceTask does not provide final callback

### ISSUE THREAD

**Issue by msak** [pleerock/gulpclass#14]
First of all, great work!

Currently I am missing a possibility to handle the final callback of sequences (run-sequence).

Even on an error 'run-sequence' calls the last function, anyway.
{quote site: https://www.npmjs.com/package/run-sequence}
If the final argument is a function, it will be used as a callback after all the functions are either finished or an error has occurred.
{quote}

But your implementation sets implicitly the callback of 'orchestrator' as last function. I could not find any way to handle errors of sequence, using the decorator @SequenceTask.

So I would recommend to allow a function as last item of an sequence like run-sequence does. And wrap it and the orchestrator callback with helper function, which will be the last function given to run-sequence.

What do you think?. Should I provide you with an PR?

many thanks, Mustafa Sak

**Comment by pleerock** [comment]
will it break/affect somehow current usage? try to provide a PR and lets see what changes will be there. I guess all you need [is this line](https://github.com/pleerock/gulpclass/blob/master/src/MetadataStorage.ts#L61)
