### ISSUE TITLE
Calling tasks does not work.

### ISSUE THREAD

**Issue by stefanwalther** [pleerock/gulpclass#3]
Hi,

running your examples and even forking gulpclass and running the build/es5/gulpfile.js always returns the following for me

``` bash
[18:59:34] Using gulpfile ~/git/_priv/projext-xxx/gulpfile.js
[18:59:34] Starting 'default'...
```

Note, that running tasks is fine, but I think in this case (similar as your example) the build task is never called:

``` ts
@SequenceTask()
    build() {
        return ["ts::compile"];
    }

    @Task()
    default() {
        return ["build"];
    }
```

Any ideas?
Cool approach by the way, really like it!

Regards
Stefan

**Comment by pleerock** [comment]
Hello,
what exactly problem do you have? From your log looks like your task is starting, but not finishing? Is typescript compilation is a part of your gulp build? If yes then you may follow advices from the README. This repository (gulpclass) itself using a bit different approach to run its tasks. You can take a look on any my open source repository  [here](https://github.com/pleerock?tab=repositories) most of them using gulpclass , try to run them

**Comment by pleerock** [comment]
closing because of no response from reporter
