### ISSUE TITLE
Import tasks from other files

### ISSUE THREAD

**Issue by ghost** [pleerock/gulpclass#5]
Is it possible to import tasks from other files. Let's say you make a file for every task and want to import those tasks in your gulpfile.ts. Can you show me how to do that with gulpfile.ts?

**Comment by pleerock** [comment]
I have updated a readme. Take a look [here](https://github.com/pleerock/gulpclass#faq)

**Comment by ghost** [comment]
Cool, thank you.

**Comment by ghost** [comment]
Would you mind to add a sample on how a task file should look like then?

**Comment by pleerock** [comment]
For now probably docs are enough, or maybe later I'll do it, or maybe someone will contribute
