### ISSUE TITLE
Default task does not execute Tasks returned in Array

### ISSUE THREAD

**Issue by ghost** [pleerock/gulpclass#6]
I have some kind of following setup. When I run `gulp` it will only execute 'default' and then stopps without running the SequenceTask.
`@SequenceTask('Build')
    Build(){
        return ['TypeScript', 'UglifyJS', 'CopyTSFiles', 'RenameMap', 'RenameTS', 'CopyFilesToCrmPackage'];
    }`
`@Task()
    default(){
        return ['Build'];
    }
`

**Comment by pleerock** [comment]
because you should use task dependency. Example is [here](https://github.com/pleerock/gulpclass)

``` typescript
@Task("default", ["Build"]) 
default(){
} 
```

**Comment by ghost** [comment]
You should update the "Usage" section also with the use of the default task.
