### ISSUE TITLE
Debugging with sourcemaps through webstorm for example?

### ISSUE THREAD

**Issue by iangregsondev** [pleerock/gulpclass#8]
Hi,

I wonder if you can help ?

I have setup everything as per the instructions and it works. I can run my gulp tasks without issues. 

I created a gulpfile.js and my actually gulpclass is stored in gulpclass.ts so to avoid any conflicts.

I tried adding inlineSourceMap and then later inlineSources and setting both to true. I also placed a breakpoint in the TS file.

Using a RUN/DEBUG configuration I setup a GULP config pointing it directly to my gulpfile.js

The breakpoint never arrives in the TS file.

If i place a breakpoint in the JS then of course this does arrive.

Here is my gulpfile.js (modified to include the sourceMaps)

var compilerOptions = {inlineSourceMap: true, inlineSources: true};

`eval(require("typescript").transpile(require("fs").readFileSync("./gulpclass.ts").toString(), compilerOptions));`

Any ideas what I could be doing wrong ?

My gulpclass.ts file is left unmodified from the example included in github and I am placing a break point in the TS file on this line

```
    return ["build"];
```

Thanks in advance

**Comment by pleerock** [comment]
I dont think its [easily] possible to do debugging here since code is running dynamically. I can suggest you to use [alternative-approaches](https://github.com/pleerock/gulpclass/blob/master/README.md#alternative-approaches) of compiling your typescript gulp file. Using these approaches you can use debugging

**Comment by iangregsondev** [comment]
Thanks, yep that worked great. I basically create a specific tsconfig for my gulpfile to keep it separate from my other src files.  Placed this in my standard gulpfile.js (root)

`require('./gulp/build/gulpfile');`

I also created a standard SH file for compiling it, called gulp-ts-compile.sh

```
#!/bin/bash
tsc -p gulp/gulp-tsconfig.json
```

Thanks again fro your help.

Debugging works great, also gulp tasks show up inside webstorm.

**Comment by pleerock** [comment]
great!
